backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

definitions: &button_fields
  - { label: "Label", name: "label", widget: "string" }
  - { label: "Title", name: "title", widget: "string" }
  - { label: "Content", name: "content", widget: "markdown" }

translation_fields: &translation_structure
  - { label: "Location", name: "location", widget: "string" }
  - label: "Button 1"
    name: "button1"
    widget: "object"
    fields: *button_fields
  - label: "Button 2"
    name: "button2"
    widget: "object"
    fields: *button_fields
  - label: "Button 3"
    name: "button3"
    widget: "object"
    fields: *button_fields

collections:
  - name: "translations"
    label: "Translations"
    files:
      - label: "English"
        name: "english"
        file: "public/locales/en.json"
        fields: *translation_structure
      
      - label: "Spanish"
        name: "spanish"
        file: "public/locales/es.json"
        fields: *translation_structure
      
      - label: "French"
        name: "french"
        file: "public/locales/fr.json"
        fields: *translation_structure
      
      - label: "Portuguese"
        name: "portuguese"
        file: "public/locales/pt.json"
        fields: *translation_structure