backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "translations"
    label: "Translations"
    files:
      - label: "English"
        name: "english"
        file: "public/locales/en.json"
        fields:
          - label: "Button 1"
            name: "button1"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
          - label: "Button 2"
            name: "button2"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
          - label: "Button 3"
            name: "button3"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }

      - label: "Spanish"
        name: "spanish"
        file: "public/locales/es.json"
        fields:
          - label: "Button 1"
            name: "button1"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
          - label: "Button 2"
            name: "button2"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
          - label: "Button 3"
            name: "button3"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }

      - label: "French"
        name: "french"
        file: "public/locales/fr.json"
        fields:
          - label: "Button 1"
            name: "button1"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
          - label: "Button 2"
            name: "button2"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
          - label: "Button 3"
            name: "button3"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
      - label: "Portuguese"
        name: "french"
        file: "public/locales/pt.json"
        fields:
          - label: "Button 1"
            name: "button1"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
          - label: "Button 2"
            name: "button2"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }
          - label: "Button 3"
            name: "button3"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Content", name: "content", widget: "markdown" }